[package]
name = "zi-input"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = { workspace = true }
chumsky.workspace = true
crossterm = { workspace = true, optional = true }
arbitrary = { workspace = true, optional = true, features = ["derive"] }

[lints]
workspace = true
